import puppeteer from 'puppeteer';
import path from 'path';
import fs from 'fs/promises';

export interface PdfOptions {
  format?: 'A4' | 'Letter';
  margins?: {
    top?: string;
    right?: string;
    bottom?: string;
    left?: string;
  };
}

export async function generatePdfFromHtml(htmlContent: string, options: PdfOptions = {}): Promise<Buffer> {
  let browser;
  
  try {
    console.log('🔄 Launching Puppeteer browser for PDF generation...');
    
    browser = await puppeteer.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--no-first-run',
        '--no-zygote',
        '--single-process',
        '--disable-gpu',
        '--disable-web-security',
        '--disable-features=VizDisplayCompositor',
        '--max-old-space-size=4096'
      ]
    });

    const page = await browser.newPage();
    
    // Set viewport for consistent rendering
    await page.setViewport({ width: 1200, height: 800 });
    
    // Enable print media type for PDF-specific styles
    await page.emulateMediaType('print');

    // Validate HTML content before setting
    console.log('📄 Validating HTML content...');
    if (!htmlContent || htmlContent.length < 100) {
      throw new Error('HTML content is empty or too short');
    }
    
    if (!htmlContent.includes('<!DOCTYPE html>')) {
      throw new Error('HTML content missing DOCTYPE declaration');
    }
    
    console.log('📄 Setting HTML content...', `(${htmlContent.length} chars)`);
    await page.setContent(htmlContent, {
      waitUntil: ['networkidle0', 'domcontentloaded'],
      timeout: 45000
    });

    // Wait for charts and dynamic content to fully render
    console.log('⏳ Waiting for charts to render...');
    try {
      // Wait for Chart.js canvases to be present
      await page.waitForSelector('canvas', { timeout: 10000 });
      console.log('📊 Found chart canvases');
    } catch (error) {
      console.log('⚠️ No charts found or timeout waiting for charts');
    }

    // Additional wait for rendering completion and chart animations
    await new Promise(resolve => setTimeout(resolve, 5000));
    console.log('✅ Content rendering complete');
    
    // Ensure all images and canvases are loaded
    await page.evaluate(() => {
      return new Promise((resolve) => {
        const images = Array.from(document.images);
        const canvases = Array.from(document.querySelectorAll('canvas'));
        
        if (images.length === 0 && canvases.length === 0) {
          resolve(true);
          return;
        }
        
        let loadedCount = 0;
        const totalCount = images.length + canvases.length;
        
        const checkComplete = () => {
          loadedCount++;
          if (loadedCount >= totalCount) {
            resolve(true);
          }
        };
        
        // Check images
        images.forEach(img => {
          if (img.complete) {
            checkComplete();
          } else {
            img.onload = checkComplete;
            img.onerror = checkComplete;
          }
        });
        
        // Assume canvases are ready (they should be after our timeout)
        canvases.forEach(() => checkComplete());
        
        // Fallback timeout
        setTimeout(() => resolve(true), 3000);
      });
    });

    console.log('🖨️ Generating PDF...');
    const pdfBuffer = await page.pdf({
      format: options.format || 'A4',
      margin: {
        top: options.margins?.top || '10px',
        right: options.margins?.right || '10px',
        bottom: options.margins?.bottom || '10px',
        left: options.margins?.left || '10px'
      },
      printBackground: true,
      preferCSSPageSize: false,
      timeout: 45000
    });

    const pdfSize = pdfBuffer.length;
    console.log(`✅ PDF generated - Size: ${(pdfSize / 1024).toFixed(2)}KB`);
    
    // Debug the buffer content
    console.log('📊 PDF buffer type:', typeof pdfBuffer);
    console.log('📊 PDF buffer is Buffer:', Buffer.isBuffer(pdfBuffer));
    console.log('📊 PDF buffer first 20 bytes:', Array.from(pdfBuffer.subarray(0, 20)));
    console.log('📊 PDF buffer as string (first 20 chars):', pdfBuffer.toString('ascii', 0, 20));
    
    // Ensure we have a proper Buffer
    const finalBuffer = Buffer.isBuffer(pdfBuffer) ? pdfBuffer : Buffer.from(pdfBuffer);
    
    // Validate the final buffer
    const header = finalBuffer.toString('ascii', 0, 8);
    if (!header.startsWith('%PDF-')) {
      console.error('⚠️ Generated PDF buffer invalid. Header:', header);
      console.error('⚠️ First 50 bytes as numbers:', Array.from(finalBuffer.subarray(0, 50)));
      throw new Error(`Invalid PDF generated by Puppeteer. Header: "${header}"`);
    }
    
    if (finalBuffer.length < 1000) {
      console.warn('⚠️ PDF seems unusually small, may be corrupted');
      throw new Error(`PDF too small: ${finalBuffer.length} bytes`);
    }
    
    console.log('✅ PDF validation passed');
    return finalBuffer;

  } catch (error) {
    console.error('❌ Error generating PDF:', error);
    throw new Error(`Failed to generate PDF: ${error instanceof Error ? error.message : 'Unknown error'}`);
  } finally {
    if (browser) {
      await browser.close();
    }
  }
}

export async function savePdfReport(htmlContent: string, reportId: string, options: PdfOptions = {}): Promise<string> {
  try {
    const pdfBuffer = await generatePdfFromHtml(htmlContent, options);
    
    // Save PDF to public directory
    const reportsDir = path.join(process.cwd(), 'public', 'reports');
    await fs.mkdir(reportsDir, { recursive: true });
    
    const pdfPath = path.join(reportsDir, `report-${reportId}.pdf`);
    await fs.writeFile(pdfPath, pdfBuffer);
    
    console.log('💾 PDF saved to:', pdfPath);
    return `/reports/report-${reportId}.pdf`;
    
  } catch (error) {
    console.error('❌ Error saving PDF report:', error);
    throw error;
  }
}

export async function createEmailAttachment(htmlContent: string, reportId: string, options: PdfOptions = {}): Promise<{ filename: string; content: Buffer }> {
  try {
    const pdfBuffer = await generatePdfFromHtml(htmlContent, options);
    
    // Validate PDF buffer
    const pdfSize = pdfBuffer.length;
    console.log(`📊 Email PDF buffer size: ${(pdfSize / 1024).toFixed(2)}KB`);
    
    if (pdfSize < 1000) {
      console.error('⚠️ PDF buffer seems too small, may be corrupted');
      throw new Error(`PDF buffer too small: ${pdfSize} bytes`);
    }
    
    // Check PDF header
    const header = pdfBuffer.toString('ascii', 0, 8);
    if (!header.startsWith('%PDF-')) {
      console.error('⚠️ PDF buffer missing valid PDF header:', header);
      throw new Error('Invalid PDF buffer - missing PDF header');
    }
    
    console.log('✅ PDF buffer validation passed');
    
    // Also save email PDF to disk for debugging
    try {
      const reportsDir = path.join(process.cwd(), 'public', 'reports');
      const debugPath = path.join(reportsDir, `email-debug-${reportId}.pdf`);
      await fs.writeFile(debugPath, pdfBuffer);
      console.log('💾 Email PDF debug copy saved to:', debugPath);
    } catch (debugError) {
      console.warn('⚠️ Could not save email PDF debug copy:', debugError);
    }
    
    return {
      filename: `${reportId}-report.pdf`,
      content: pdfBuffer
    };
    
  } catch (error) {
    console.error('❌ Error creating PDF email attachment:', error);
    throw error;
  }
}