import { ReportConfig } from '@/types';

export async function generateReport(data: Record<string, unknown>[], summary: string, config: ReportConfig): Promise<string> {
  // Generate chart data
  const chartData = data.slice(0, 10).map((item, index) => ({
    name: String(item.campaign_name || item.ad_name || `Item ${index + 1}`),
    spend: parseFloat(String(item.spend)) || 0,
    impressions: parseInt(String(item.impressions)) || 0,
    clicks: parseInt(String(item.clicks)) || 0,
  }));

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${config.platform.toUpperCase()} Insight Report</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f8fafc;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 12px;
            margin-bottom: 30px;
            text-align: center;
        }
        .header h1 {
            margin: 0 0 10px 0;
            font-size: 2.5em;
        }
        .header p {
            margin: 0;
            opacity: 0.9;
        }
        .summary {
            background: white;
            padding: 30px;
            border-radius: 12px;
            margin-bottom: 30px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
        }
        .chart-container {
            background: white;
            padding: 30px;
            border-radius: 12px;
            margin-bottom: 30px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
        }
        .chart-container h2 {
            color: #374151;
            margin-top: 0;
        }
        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        .metric-card {
            background: white;
            padding: 20px;
            border-radius: 12px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
            text-align: center;
        }
        .metric-value {
            font-size: 2em;
            font-weight: bold;
            color: #4f46e5;
            margin: 10px 0;
        }
        .metric-label {
            color: #6b7280;
            font-size: 0.9em;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }
        .data-table {
            background: white;
            border-radius: 12px;
            overflow: hidden;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
        }
        .data-table h2 {
            background: #f8fafc;
            margin: 0;
            padding: 20px 30px;
            color: #374151;
            border-bottom: 1px solid #e5e7eb;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 12px 16px;
            text-align: left;
            border-bottom: 1px solid #e5e7eb;
        }
        th {
            background-color: #f8fafc;
            font-weight: 600;
            color: #374151;
        }
        tr:hover {
            background-color: #f8fafc;
        }
        .footer {
            text-align: center;
            color: #6b7280;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
        }
        canvas {
            max-height: 400px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>${config.platform.toUpperCase()} Insight Report</h1>
        <p>Generated on ${new Date().toLocaleDateString()} • ${config.dateRangeEnum.replace('last', 'Last ').replace(/(\d+)/, '$1 days')}</p>
    </div>

    ${generateMetricsCards(data)}

    <div class="summary">
        <h2 style="color: #374151; margin-top: 0;">Executive Summary</h2>
        <div style="white-space: pre-line;">${summary}</div>
    </div>

    <div class="chart-container">
        <h2>Performance Overview</h2>
        <canvas id="performanceChart"></canvas>
    </div>

    <div class="data-table">
        <h2>Detailed Data</h2>
        <div style="overflow-x: auto;">
            ${generateDataTable(data)}
        </div>
    </div>

    <div class="footer">
        <p>Report generated by Scheduled Insight Reports</p>
        <p>Data sourced from ${config.platform.toUpperCase()} API</p>
    </div>

    <script>
        const ctx = document.getElementById('performanceChart').getContext('2d');
        const chart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: ${JSON.stringify(chartData.map(d => d.name))},
                datasets: [
                    {
                        label: 'Spend ($)',
                        data: ${JSON.stringify(chartData.map(d => d.spend))},
                        backgroundColor: 'rgba(99, 102, 241, 0.8)',
                        borderColor: 'rgba(99, 102, 241, 1)',
                        borderWidth: 1,
                        yAxisID: 'y',
                    },
                    {
                        label: 'Impressions',
                        data: ${JSON.stringify(chartData.map(d => d.impressions))},
                        backgroundColor: 'rgba(34, 197, 94, 0.8)',
                        borderColor: 'rgba(34, 197, 94, 1)',
                        borderWidth: 1,
                        yAxisID: 'y1',
                    }
                ]
            },
            options: {
                responsive: true,
                plugins: {
                    title: {
                        display: true,
                        text: '${config.platform.toUpperCase()} Performance Data'
                    },
                    legend: {
                        position: 'top',
                    }
                },
                scales: {
                    y: {
                        type: 'linear',
                        display: true,
                        position: 'left',
                        title: {
                            display: true,
                            text: 'Spend ($)'
                        }
                    },
                    y1: {
                        type: 'linear',
                        display: true,
                        position: 'right',
                        title: {
                            display: true,
                            text: 'Impressions'
                        },
                        grid: {
                            drawOnChartArea: false,
                        },
                    }
                }
            }
        });
    </script>
</body>
</html>`;

  return html;
}

function generateMetricsCards(data: Record<string, unknown>[]): string {
  const totalSpend = data.reduce((sum, item) => sum + (parseFloat(String(item.spend)) || 0), 0);
  const totalImpressions = data.reduce((sum, item) => sum + (parseInt(String(item.impressions)) || 0), 0);
  const totalClicks = data.reduce((sum, item) => sum + (parseInt(String(item.clicks)) || 0), 0);
  const avgCTR = totalImpressions > 0 ? ((totalClicks / totalImpressions) * 100) : 0;

  return `
    <div class="metrics-grid">
        <div class="metric-card">
            <div class="metric-label">Total Spend</div>
            <div class="metric-value">$${totalSpend.toFixed(2)}</div>
        </div>
        <div class="metric-card">
            <div class="metric-label">Total Impressions</div>
            <div class="metric-value">${totalImpressions.toLocaleString()}</div>
        </div>
        <div class="metric-card">
            <div class="metric-label">Total Clicks</div>
            <div class="metric-value">${totalClicks.toLocaleString()}</div>
        </div>
        <div class="metric-card">
            <div class="metric-label">Average CTR</div>
            <div class="metric-value">${avgCTR.toFixed(2)}%</div>
        </div>
    </div>
  `;
}

function generateDataTable(data: Record<string, unknown>[]): string {
  if (!data || data.length === 0) {
    return '<p>No data available</p>';
  }

  const headers = Object.keys(data[0]);
  const maxRows = Math.min(data.length, 20); // Limit to first 20 rows

  return `
    <table>
        <thead>
            <tr>
                ${headers.map(header => `<th>${header.replace(/_/g, ' ').toUpperCase()}</th>`).join('')}
            </tr>
        </thead>
        <tbody>
            ${data.slice(0, maxRows).map(row => `
                <tr>
                    ${headers.map(header => `<td>${formatValue(row[header])}</td>`).join('')}
                </tr>
            `).join('')}
        </tbody>
    </table>
    ${data.length > maxRows ? `<p style="padding: 20px; text-align: center; color: #6b7280;">Showing first ${maxRows} of ${data.length} rows</p>` : ''}
  `;
}

function formatValue(value: unknown): string {
  if (value === null || value === undefined) return '-';
  if (typeof value === 'number') {
    if (value % 1 !== 0) {
      return value.toFixed(2);
    }
    return value.toLocaleString();
  }
  return String(value);
}

export const reportGenerator = {
  generateReport
};